package com.accuity.zeus.aft.commons;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Created by soofis on 8/12/2015.
 */
public class DataManagementAppVals {

    public static List<String> expCountryListVal = new ArrayList<>(Arrays.asList(
            "Choose a Country",
            "Afghanistan",
            "Åland Islands",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antigua & Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bonaire, Sint Eustatius and Saba",
            "Bosnia-Herzegovina",
            "Botswana",
            "Brazil",
            "British Indian Ocean Territory",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island (Indian Ocean)",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Congo (Democratic Republic of)",
            "Congo (Republic of)",
            "Cook Islands",
            "Costa Rica",
            "Côte d'Ivoire",
            "Croatia",
            "Cuba",
            "Curaçao",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Falkland Islands",
            "Faroe Islands",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea (Democratic People's Republic of)",
            "Korea (Republic of)",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macau",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte Island",
            "Mexico",
            "Micronesia (Federated States of)",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Reunion Island",
            "Romania",
            "Rwanda",
            "Saint Helena, Ascension and Tristan da Cunha",
            "Samoa",
            "San Marino",
            "São Tomé & Príncipe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Sint Maarten",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "St Barthélemy",
            "St Kitts & Nevis",
            "St Lucia",
            "St Martin",
            "St Vincent & the Grenadines",
            "St. Pierre et Miquelon",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tonga",
            "Trinidad & Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks & Caicos Islands",
            "Tuvalu",
            "UAE",
            "Uganda",
            "UK",
            "Ukraine",
            "Uruguay",
            "USA",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City State (Holy See)",
            "Venezuela",
            "Vietnam",
            "Virgin Islands (British)",
            "Virgin Islands (US)",
            "Wallis and Futuna",
            "Western Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe"
            ));

        public static List<String> expTaxonomiesListVal = new ArrayList<>(Arrays.asList(
                "Abbreviation Rules",
                "Additional Info Text Type",
                "Area Alternative Regions",
                "Area Related Entity Type",
                "Area Related Person Type",
                "Area Related Place Sub-Type",
                "Area Related Place Type",
                "City Alternative Regions",
                "City Related Entity Type",
                "City Related Place Sub-Type",
                "City Related Place Type",
                "Continents",
                "Country Alternative Regions",
                "Country Name Type",
                "Country Related Entity Type",
                "Country Related Person Type",
                "Country Related Place Sub-Type",
                "Country Related Place Type",
                "Default SWIFT BIC Pairings",
                "Demographics Metrics",
                "Edit Type",
                "Federal Reserve Branch Districts",
                "Federal Reserve Branch Districts",
                "Federal Reserve Districts",
                "Financial Services",
                "Geographical Third Party Identifiers",
                "Language",
                "Legal Entity Charter Type",
                "Legal Entity FATCA Status",
                "Legal Entity Insurance Type",
                "Legal Entity Name Type",
                "Legal Entity Organisation Type",
                "Legal Entity Third Party Identifiers",
                "Metropolitan Statistical Region",
                "National Credit Union Administration Region",
                "Office Third Party Identifiers",
                "Ownership Summary Text Type",
                "Personnel Summary Text Type",
                "Place Name Type",
                "Rating Agencies",
                "Rating Types",
                "Routing Code Type",
                "Routing Code Type",
                "SEPA Status",
                "Service Categories",
                "SSI Type Hierarchy",
                "Status",
                "Telecom Type",
                "Time Zones",
                "Trading Regions"
        ));
}
